"""create guests

Revision ID: 4c11aa8d0d8d
Revises: 44693fa6e7f7
Create Date: 2025-05-21 13:08:08.303012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '4c11aa8d0d8d'
down_revision: Union[str, None] = '44693fa6e7f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'guests',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('isPresent', sa.Boolean(), nullable=False),
        sa.Column('table_id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(['table_id'], ['tables.id'], onupdate='CASCADE', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guests')
    # ### end Alembic commands ###
