"""create tables

Revision ID: 44693fa6e7f7
Revises: 
Create Date: 2025-05-21 13:03:29.045931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '44693fa6e7f7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'tables',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('num', sa.Integer(), nullable=False),
        sa.Column('description', sa.String(), nullable=False),
        sa.Column('max_guests', sa.INTEGER(), nullable=False),
        sa.CheckConstraint('max_guests > 0', name='max_guests_positive'),
        sa.CheckConstraint('num > 0', name='num_positive'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('num')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tables')
    # ### end Alembic commands ###
